{
 "title": "Gateway API State",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Gateway Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of GatewayClasses across all clusters",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gatewayclass_info)"
    }
   ]
  },
  {
   "title": "GatewayClasses",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gatewayclass_created"
    }
   ]
  },
  {
   "title": "GatewayClass Instances",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(gatewayclass_name) (gatewayapi_gateway_info)"
    }
   ]
  },
  { "title": "Gateways", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of Gateways across all namespaces",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(gatewayapi_gateway_info)" }
   ]
  },
  {
   "title": "Unhealthy",
   "type": "stat",
   "description": "Number of Gateways not in an Accepted and Programmed state",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((gatewayapi_gateway_status{type=\"Accepted\"} == 0) or (gatewayapi_gateway_status{type=\"Programmed\"} == 0)) or vector(0)"
    }
   ]
  },
  {
   "title": "Gateways",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_created * on(name, namespace, instance) group_right gatewayapi_gateway_info"
    }
   ]
  },
  {
   "title": "Gateway Listeners",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_listener_info"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Total Gateways with an Accepted state of True",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_status{type=\"Accepted\"} > 0)"
    }
   ]
  },
  {
   "title": "Programmed",
   "type": "stat",
   "description": "Total Gateways with a Programmed state of True",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_status{type=\"Programmed\"} > 0)"
    }
   ]
  },
  {
   "title": "Listeners",
   "type": "stat",
   "description": "Total number of listeners across all Gateways",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gateway_listener_info)"
    }
   ]
  },
  {
   "title": "Att. Routes",
   "type": "stat",
   "description": "Total number of attached routes across all listeners",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gatewayapi_gateway_status_listener_attached_routes)"
    }
   ]
  },
  {
   "title": "Gateway Status Addresses",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_status_address_info"
    }
   ]
  },
  {
   "title": "Gateway Listener Status - Attached Routes",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gateway_status_listener_attached_routes"
    }
   ]
  },
  { "title": "HTTPRoutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of HTTPRoutes across all namespaces",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_httproute_created)"
    }
   ]
  },
  {
   "title": "Tar. Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) targeted by HTTPRoutes",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_httproute_parent_info)"
    }
   ]
  },
  {
   "title": "HTTPRoutes",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gatewayapi_httproute_created" }
   ]
  },
  {
   "title": "HTTPRoute *targeted* Parent References",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_httproute_parent_info"
    }
   ]
  },
  {
   "title": "Att. Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) attached to HTTPRoutes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_httproute_status_parent_info)"
    }
   ]
  },
  {
   "title": "HTTPRoute *attached* Parent References",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_httproute_status_parent_info"
    }
   ]
  }
 ]
}