{
 "title": "Gateway API State / GatewayClasses",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "gatewayclass",
    "query": {
     "query": "label_values(gatewayapi_gatewayclass_info, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gateway Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of GatewayClasses across all clusters",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gatewayclass_info)"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Total GatewayClasses with an Accepted state of True",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gatewayclass_status{type=\"Accepted\"} > 0)"
    }
   ]
  },
  {
   "title": "GatewayClasses",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_gatewayclass_created"
    }
   ]
  },
  {
   "title": "Gateways (by GatewayClass)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gatewayapi_gateway_info" }
   ]
  },
  {
   "title": "Supported Features (by GatewayClass)",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "gatewayapi_gatewayclass_status_supported_features{name=\"$gatewayclass\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}