{
 "title": "Gateway API State / TCPRoutes",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "tcproute",
    "label": "TCPRoute",
    "query": {
     "query": "label_values(gatewayapi_tcproute_created, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "TCPRoutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of TCPRoutes across all namespaces",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(gatewayapi_tcproute_created{name=~\"${tcproute}\"})"
    }
   ]
  },
  {
   "title": "Tar. Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) targeted by TCPRoutes",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "count(gatewayapi_tcproute_parent_info{name=~\"${tcproute}\"})"
    }
   ]
  },
  {
   "title": "TCPRoutes",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "gatewayapi_tcproute_created{name=~\"${tcproute}\"}"
    }
   ]
  },
  {
   "title": "TCPRoute *targeted* Parent References",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "gatewayapi_tcproute_parent_info{name=~\"${tcproute}\"}"
    }
   ]
  },
  {
   "title": "Att. Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) attached to TCPRoutes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "count(gatewayapi_tcproute_status_parent_info{name=~\"${tcproute}\"})"
    }
   ]
  },
  {
   "title": "TCPRoute *attached* Parent References",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "gatewayapi_tcproute_status_parent_info{name=~\"${tcproute}\"}"
    }
   ]
  }
 ]
}