{
 "title": "Gateway API State / UDPRoutes",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "udproute",
    "label": "UDPRoute",
    "query": {
     "query": "label_values(gatewayapi_udproute_created, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "UDPRoutes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of UDPRoutes across all namespaces",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_udproute_created{name=~\"${udproute}\"})"
    }
   ]
  },
  {
   "title": "Tar. Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) targeted by UDPRoutes",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_udproute_parent_info{name=~\"${udproute}\"})"
    }
   ]
  },
  {
   "title": "UDPRoutes",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_udproute_created{name=~\"${udproute}\"}"
    }
   ]
  },
  {
   "title": "UDPRoute *targeted* Parent References",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_udproute_parent_info{name=~\"${udproute}\"}"
    }
   ]
  },
  {
   "title": "Att. Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) attached to UDPRoutes",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_udproute_status_parent_info{name=~\"${udproute}\"})"
    }
   ]
  },
  {
   "title": "UDPRoute *attached* Parent References",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "gatewayapi_udproute_status_parent_info{name=~\"${udproute}\"}"
    }
   ]
  }
 ]
}