apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/prometheus-operator/kube-prometheus?ref=release-0.11
# Use the github url instead of the relative path if using this outside the repo
#  - github.com/kuadrant/gateway-api-state-metrics?ref=<release>
  - ../../default
# Include the example dashboars and rules if you want
  - ../dashboards
  - ../rules

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: kube-state-metrics
    path: ksm_deployment_patch.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: kube-state-metrics
    path: ksm_clusterrole_patch.yaml
# Patch grafana deployment to include dashboard configmaps
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
    path: grafana_deployment_patch.yaml
