- op: add
  path: /rules/-
  value:
    apiGroups:
    - "apiextensions.k8s.io"
    resources:
    - customresourcedefinitions
    verbs:
    - list
    - watch
- op: add
  path: /rules/-
  value:
    apiGroups:
    - "kuadrant.io"
    resources:
    - tlspolicies
    - dnspolicies
    - ratelimitpolicies
    - authpolicies
    - dnsrecords
    - dnshealthcheckprobes
    verbs:
    - list
    - watch
