    - groupVersionKind:
        group: kuadrant.io
        kind: "TLSPolicy"
        version: "v1alpha1"
      metricNamePrefix: gatewayapi_tlspolicy
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "target_info"
        help: "Target references that the tlspolicy wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, targetRef]
            labelsFromPath:
              target_group: ["group"]
              target_kind: ["kind"]
              target_name: ["name"]
              target_namespace: ["namespace"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
    - groupVersionKind:
        group: kuadrant.io
        kind: "DNSPolicy"
        version: "v1alpha1"
      metricNamePrefix: gatewayapi_dnspolicy
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "target_info"
        help: "Target references that the dnspolicy wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, targetRef]
            labelsFromPath:
              target_group: ["group"]
              target_kind: ["kind"]
              target_name: ["name"]
              target_namespace: ["namespace"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
    - groupVersionKind:
        group: kuadrant.io
        kind: "RateLimitPolicy"
        version: "v1beta2"
      metricNamePrefix: gatewayapi_ratelimitpolicy
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "target_info"
        help: "Target references that the tlspolicy wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, targetRef]
            labelsFromPath:
              target_group: ["group"]
              target_kind: ["kind"]
              target_name: ["name"]
              target_namespace: ["namespace"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
    - groupVersionKind:
        group: kuadrant.io
        kind: "AuthPolicy"
        version: "v1beta2"
      metricNamePrefix: gatewayapi_authpolicy
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace
      metrics:
      - name: "labels"
        help: "Kubernetes labels converted to Prometheus labels."
        each:
          type: Info
          info:
            path: [metadata]
            labelsFromPath:
              "*": [labels]
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]
      - name: "deleted"
        help: "deletion timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, deletionTimestamp]
      - name: "target_info"
        help: "Target references that the authpolicy wants to be attached to"
        each:
          type: Info
          info:
            path: [spec, targetRef]
            labelsFromPath:
              target_group: ["group"]
              target_kind: ["kind"]
              target_name: ["name"]
              target_namespace: ["namespace"]
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
    - groupVersionKind:
        group: kuadrant.io
        kind: "DNSRecord"
        version: "v1alpha1"
      metricNamePrefix: kuadrant_dnsrecord            
      labelsFromPath:
        name:
        - metadata
        - name
        namespace:
        - metadata
        - namespace 
        rootDomain:
        - spec
        - rootHost     
      metrics:
      - name: "created"
        help: "created timestamp"
        each:
          type: Gauge
          gauge:
            path: [metadata, creationTimestamp]      
      - name: "status_root_domain_owners"
        help: "root domain owners (the ids of controllers managing this root domain)"
        each:
          type: Info
          info:
            path: [status, domainOwners]
            labelsFromPath:
              owner: []
      - name: "status"
        help: "status condition"
        each:
          type: Gauge
          gauge:
            path: [status, conditions]
            labelsFromPath:
              type: ["type"]
            valueFrom: ["status"]
