apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: external
  namespace: istio-system
spec:
  targetRef:
    name: external
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
status:
  conditions:
  - lastTransitionTime: "2023-08-21T22:53:08Z"
    message: Gateway is TLS Enabled
    reason: GatewayTLSEnabled
    status: "True"
    type: Ready
---
apiVersion: kuadrant.io/v1
kind: TLSPolicy
metadata:
  name: internal
  namespace: istio-system
spec:
  targetRef:
    name: internal
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
status:
  conditions:
  - lastTransitionTime: "2023-08-21T22:53:08Z"
    message: Gateway is TLS Enabled
    reason: GatewayTLSEnabled
    status: "True"
    type: Ready
---
apiVersion: kuadrant.io/v1
kind: DNSPolicy
metadata:
  name: external
  namespace: istio-system
spec:
  loadBalancing:
    defaultGeo: true
    geo: US
    weight: 120
  providerRefs:
    - name: aws-credentials
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: external
status:
  conditions:
  - lastTransitionTime: "2023-11-13T17:11:41Z"
    message: Gateway is DNS Enabled
    reason: GatewayDNSEnabled
    status: "True"
    type: Ready
  observedGeneration: 1
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: rlp-www
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: www
  limits:
    alice-limit:
      rates:
        - limit: 5
          window: 10s
      when:
        - predicate: auth.identity.userid == 'alice'
    bob-limit:
      rates:
        - limit: 2
          window: 10s
      when:
        - predicate: auth.identity.userid == 'bob'
status:
  conditions:
  - lastTransitionTime: "2023-08-21T22:53:08Z"
    message: HTTPRoute is ratelimited
    reason: HTTPRouteProtected
    status: "True"
    type: Available
---
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: rlp-cdn
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: cdn
  limits:
    alice-limit:
      rates:
        - limit: 5
          window: 10s
      when:
        - predicate: auth.identity.userid == 'alice'
    bob-limit:
      rates:
        - limit: 2
          window: 10s
      when:
        - predicate: auth.identity.userid == 'bob'
status:
  conditions:
  - lastTransitionTime: "2023-08-21T22:53:08Z"
    message: HTTPRoute is ratelimited
    reason: HTTPRouteProtected
    status: "True"
    type: Available
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: dashboards-protection
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: dashboards
  rules:
    authentication:
      api-key-users:
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: toystore
        credentials:
          authorizationHeader:
            prefix: APIKEY
        metrics: false
        priority: 0
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
            metrics: false
            priority: 0
status:
  conditions:
  - lastTransitionTime: "2023-08-21T22:53:08Z"
    message: HTTPRoute is protected
    reason: HTTPRouteProtected
    status: "True"
    type: Available
---
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: accounts
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: accounts
  rules:
    authentication:
      api-key-users:
        apiKey:
          allNamespaces: true
          selector:
            matchLabels:
              app: toystore
        credentials:
          authorizationHeader:
            prefix: APIKEY
        metrics: false
        priority: 0
    response:
      success:
        filters:
          identity:
            json:
              properties:
                userid:
                  selector: auth.identity.metadata.annotations.secret\.kuadrant\.io/user-id
            metrics: false
            priority: 0
status:
  conditions:
  - lastTransitionTime: "2023-08-21T22:53:08Z"
    message: HTTPRoute is protected
    reason: HTTPRouteProtected
    status: "True"
    type: Available