apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: custom-resource-state
  namespace: monitoring
  files:
  - custom-resource-state.yaml
