name: continuous-integration

on:
  push:
    branches:
    - main
    - release*
    tags:
    - v1.*
    - v2.*
  pull_request:
    branches:
    - main
    - release*

permissions:
  contents: read

env:
  E2E_SETUP_KIND: yes
  E2E_SETUP_KUBECTL: yes
  SUDO: sudo
  GO_VERSION: "^1.20"

jobs:
  ci-e2e-tests:
    name: ci-e2e-tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: End-to-end tests
      run: |
        make test
        
  check-bundles:
    name: check-bundles
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Download Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        mv kustomize /usr/local/bin/
    - name: Compare Bundles
      run: |
          if ! make compare-bundles; then
            echo "::error:: Bundles comparison failed. Please run 'make generate-bundles' and check in changes."
            exit 1
          fi