name: continuous-integration

on:
  push:
    branches:
    - main
    - release*
    tags:
    - v1.*
    - v2.*
  pull_request:
    branches:
    - main
    - release*
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: read

env:
  E2E_SETUP_KIND: yes
  E2E_SETUP_KUBECTL: yes
  SUDO: sudo
  GO_VERSION: "^1.20"

jobs:
  ci-e2e-tests:
    name: ci-e2e-tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
      id: go

    - name: End-to-end tests
      run: |
        make test
        
  check-bundles:
    name: check-bundles
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Download Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        mv kustomize /usr/local/bin/
    - name: Compare Bundles
      run: |
          if ! make compare-bundles; then
            echo "::error:: Bundles comparison failed. Please run 'make generate-bundles' and check in changes."
            exit 1
          fi

  check-kuadrant-custom-resource-state:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Execute generation script
      run: ./hack/gen_kuadrant_custom_resource_state.sh

    - name: Check for changes in generated file
      run: |
        if ! git diff --exit-code ./config/kuadrant/custom-resource-state.yaml; then
          echo "The generated file ./config/kuadrant/custom-resource-state.yaml has changes."
          echo "Please run './hack/gen_kuadrant_custom_resource_state.sh' locally and check in the changes."
          exit 1
        fi

  required-checks:
    name: continuous-integration Required Checks
    # This check adds a list of checks to one job to simplify adding settings to the repo.
    # If a new check is added in this file, and it should be retested on entry to the merge queue,
    # it needs to be added to the list below aka needs: [ existing check 1, existing check 2, new check ].
    needs: [ ci-e2e-tests, check-bundles, check-kuadrant-custom-resource-state]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo '${{ toJSON(needs) }}' | jq -e 'all(.[]; .result == "success" or .result == "skipped")'
